In [2]:
#enumerate function，将输出按照一个序列标记出来
animals=['cat','dog','fish']
for idx,animal in enumerate(animals):
    print('#%d:%s' %(idx+1,animal))
#此处的%d表示格式化为 %s表示格式化为字符串类型

#1:cat
#2:dog
#3:fish


In [4]:
#list 表示法
nums=[0,1,2,3,4]
squares=[x**2 for x in nums]
print(squares)
even_squares=[x**2 for x in nums if x%2 ==0]
print(even_squares)

[0, 1, 4, 9, 16]
[0, 4, 16]


In [7]:
#dictinary 用法
d={'cat':'cute','dog':'furry'}
print(d['cat'])
print('cat' in d)
d['fish']='wet'
print(d['fish'])
print(d.get('moneky','N/A'))
print (d.get('fist','N/A'))

cute
True
wet
N/A
N/A


In [8]:
#functions 注意要使用elif
def sign(x):
    if x>0:
        return "+"
    elif x<0:
        return "-"
    else:
        return "0"
    
for x in [-1,0,1]:
    print (sign(x))

-
0
+


In [11]:
#class的应用
class Greeter(object):
    def __init__(self,name):
        self.name=name
    #初始化self的属性

    def greet(self,loud=False):
        if loud:
            print('Hello, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)
g=Greeter('Fred')
g.greet()
g.greet(loud=True)                

Hello, Fred
Hello, FRED!


In [18]:
#array部分
import numpy as np
a=np.array([1,2,3])
print(type(a))
print(a.shape)
#print (a.shape[0],a.shape[1])
#试错，以为数组的shape只有一个量，即为（列数，）这种形式
print (a.shape[0])
print(a)
b=np.array([[1,2,3],[4,5,6]])
#数组的最外围的框要用[ ]来表示
print(b.shape)
print(b)


<class 'numpy.ndarray'>
(3,)
3
[1 2 3]
(2, 3)
[[1 2 3]
 [4 5 6]]


In [29]:
#一些已有的创建数组的命令
import numpy as np

a=np.zeros((2,2))#创造一个2*2的0数组
print(a)

b=np.ones((1,2))#1*2的全1数组
print(b)

c=np.full((2,2),7)#全为某个元素的矩阵
print(c)

d=np.eye(2)#eye即I，单位矩阵
print(d)

e=np.random.random((2,2))
#注意radom当中还有很多其他函数，想使用随机功能的时候，调用的是
#random.random，不只是random
print (e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.75412154 0.98850101]
 [0.00839193 0.71427945]]


In [31]:
#array indexing
#切割or取定长的数列
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
b[0, 0] = 77  
#注意***，b写作a的一个切片时候，指向的也完全是a中的数据，
#改变b的值时候，a的值也同样会改变
print(a[0, 1]) 

77


In [33]:
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])


row_r1 = a[1, :]    
row_r2 = a[1:2, :] 
#写成a：b形式的时候，实际上取的是后者b那一列/行
print(row_r1, row_r1.shape)  
print(row_r2, row_r2.shape)  

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape) 
print(col_r2, col_r2.shape) 
#由结果可以看出，取出单行或者单列的时候，shape都是（a,)
#a为列或者行的维数

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [34]:
#利用下标进行输出
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
#原本的a是一个3*2的数组
print(a[[0, 1, 2], [0, 1, 0]]) 

print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  
#具体给出了待选的元素
#注意 这两个输出所表示的含义相同

print(a[[0, 0], [1, 1]]) 


print(np.array([a[0, 1], a[0, 1]])) 
#总结一下，当写作a[[],[]]的时候，两个[]中
#分别存放的是行下边和列下标，用来定位待选取的元素

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [35]:
import numpy as np


a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b])
#意思为，用b中的元素来做下标，从a的每一行都选出一个元素
a[np.arange(4), b] += 10
#将所选的元素+10并且直接改变的是a
print(a)  

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [36]:
#布尔型下标缩影
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
bool_idx = (a > 2) 
#直接存放的是整个index
print(a[bool_idx]) 
print(a[a > 2])     

[3 4 5 6]
[3 4 5 6]


In [45]:
#不同类型的数据
import numpy as np
x = np.array([1, 2])   
print(x.dtype)         

x = np.array([1.0, 2.0])   
print(x.dtype)            

x = np.array([1, 2], dtype=np.int64)   
#固定了形式
print(x.dtype)     



int32
float64
int64


In [49]:
#数组数学部分
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x + y)
print(np.add(x, y))


print(x - y)
print(np.subtract(x, y))


print(x * y)
print(np.multiply(x, y))


print(x / y)
print(np.divide(x, y))

print(np.sqrt(x))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [51]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])



print(v.dot(w))
print(np.dot(v, w))
#对于向量来说，.dot为做向量内积


print(x.dot(v))
print(np.dot(x, v))
#矩阵和向量的乘积


print(x.dot(y))
print(np.dot(x, y))
#矩阵和矩阵的乘积

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [53]:
#非常有用的sum函数***
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  
print(np.sum(x, axis=0))  
print(np.sum(x, axis=1)) 
#.sum：所有元素想加
#.sum(axis=0,按列相加)
#.sum(axis=1,按行相加)

10
[4 6]
[3 7]


In [54]:
#转置
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    
print(x.T)  


v = np.array([1,2,3])
print(v)   
print(v.T) 
#对1维的数组做转置是不会发生变化的

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [55]:
#非常重要的广播机制：
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   

#x是一个4*3的数组
#v是一个1*3的数组
#y是一个和x一样的4*3的空数组


for i in range(4):
    y[i, :] = x[i, :] + v
    #将v加到x的每一行，并赋值给y


print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [57]:
#接上面的引入广播机制，当矩阵很大时，做循环会很慢，所有了广播
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1)) 
#意为将v堆叠起来 每一行都是一个v
print(vv)  

y = x + vv 
print(y)  

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [58]:
#真正的broadcast
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v 
print(y)  

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [59]:
#broadcast的一些应用
import numpy as np


v = np.array([1,2,3])  # v 的shape为 (3,)
w = np.array([4,5])    # w 的shape为(2,)

print(np.reshape(v, (3, 1)) * w)


x = np.array([[1,2,3], [4,5,6]])
#将v加到每一行
print(x + v)


print((x.T + w).T)

print(x + np.reshape(w, (2, 1)))


print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
